security:
    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern: ^/login$
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /
            remember_me:
                secret:     %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }